"""Windows 自動取り込み（Phase 3.75 §15 / §16）。

選定: **Windows Task Scheduler の bounded scheduled invocation**（5 分間隔、ユーザー権限、
`processor --once`）。常駐 daemon / filesystem watcher は作らない（fragile）。
- restart-safe: タスクは OS が再登録不要で保持。rerun-safe: processor は idempotent。
- bounded: max_files / time_budget / single-instance lock。busy wait なし。
- 管理者権限不要（/RU を付けない = 現在ユーザー）。
本モジュールはコマンドとスクリプトを **生成する** だけで、この環境では実行しない。
"""
from __future__ import annotations

import os
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

from .config import MobileIntakeConfig

RUN_SCRIPT = "run_intake.cmd"
INSTANCE_LOCK = "processor.lock"
PROCESSOR_MODULE = "src.intelligence.mobile_intake.processor"


def processor_command(python_exe: str, repo_root: Path) -> str:
    return f'"{python_exe}" -m {PROCESSOR_MODULE} --once'


def run_script_text(python_exe: str, repo_root: Path, home: Path) -> str:
    """機械ローカル home に置く .cmd（絶対 path を含んでよい。repository には入れない）。"""
    return (
        "@echo off\r\n"
        "rem Compass mobile intake - bounded single run (generated by setup init)\r\n"
        f'cd /d "{repo_root}"\r\n'
        f'set COMPASS_INTAKE_HOME={home}\r\n'
        f'{processor_command(python_exe, repo_root)} >> "{home}\\processor.log" 2>&1\r\n'
    )


def write_run_script(home: Path, python_exe: str, repo_root: Path) -> Path:
    home = Path(home)
    home.mkdir(parents=True, exist_ok=True)
    path = home / RUN_SCRIPT
    path.write_text(run_script_text(python_exe, repo_root, home), encoding="utf-8")
    return path


def schtasks_create_command(config: MobileIntakeConfig, home: Path) -> str:
    """ユーザー権限で 5 分ごとに run_intake.cmd を起動する（管理者不要・/F で再登録可）。"""
    script = Path(home) / RUN_SCRIPT
    return (f'schtasks /Create /F /SC MINUTE /MO {config.scheduler_interval_minutes} '
            f'/TN "{config.task_name}" /TR "\\"{script}\\""')


def schtasks_delete_command(config: MobileIntakeConfig) -> str:
    return f'schtasks /Delete /F /TN "{config.task_name}"'


def schtasks_query_command(config: MobileIntakeConfig) -> str:
    return f'schtasks /Query /TN "{config.task_name}"'


def is_task_registered(config: MobileIntakeConfig, runner=subprocess.run) -> Optional[bool]:
    """Windows で schtasks が使えれば True/False、使えなければ None（Linux / macOS）。"""
    if os.name != "nt":
        return None
    try:
        rc = runner(["schtasks", "/Query", "/TN", config.task_name], capture_output=True,
                    timeout=15).returncode
    except (OSError, subprocess.SubprocessError):
        return None
    return rc == 0


# ------------------------------------------------------------- single-instance guard

def acquire_instance_lock(home: Path, stale_minutes: int, now: Optional[datetime] = None
                          ) -> Optional[Path]:
    """<home>/processor.lock を排他作成。stale（crash 残骸）なら回収して取り直す。"""
    home = Path(home)
    home.mkdir(parents=True, exist_ok=True)
    lock = home / INSTANCE_LOCK
    now = now or datetime.now(timezone.utc)
    if lock.exists():
        try:
            age = now.timestamp() - lock.stat().st_mtime
        except OSError:
            age = 0
        if age > stale_minutes * 60:
            try:
                lock.unlink()
            except OSError:
                return None
        else:
            return None
    try:
        fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
    except FileExistsError:
        return None
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(f"{os.getpid()} {now.isoformat()}\n")
    return lock


def release_instance_lock(lock: Optional[Path]) -> None:
    if lock is not None:
        try:
            lock.unlink()
        except FileNotFoundError:
            pass


def design_summary(config: MobileIntakeConfig) -> Dict[str, object]:
    return {"mechanism": "Windows Task Scheduler (bounded scheduled invocation, user-level)",
            "interval_minutes": config.scheduler_interval_minutes, "task_name": config.task_name,
            "restart_safe": True, "rerun_safe": True,
            "bounded": {"max_files_per_run": config.max_files_per_run,
                        "time_budget_seconds": config.time_budget_seconds,
                        "single_instance_lock": INSTANCE_LOCK},
            "busy_waiting": False, "daemon": False, "admin_required": False,
            "repository_mutation": False,
            "rejected": ["always-running watcher daemon (fragile)", "startup background process",
                         "public upload endpoint"]}
