"""P2-E校正fixture（ラベル付き・ja/en・曖昧語negative含む）。

METRIC LANGUAGE: ここで測るのは **fixture precision / fixture recall**。
production（実corpus）のprecision/recallではない（人手レビュー無しに主張しない）。

expect_* は本カタログ/taxonomyの範囲で「付くべきもの全て」（それ以外が付いたら
false positive）。曖昧・判定不能ケースは expect空 = 「何も付けないのが正解」。
"""

CALIBRATION = [
    # ---- AI / semiconductor ----
    dict(headline="Nvidia earnings beat estimates as AI chip demand surges",
         summary="The semiconductor giant posted record data center revenue.",
         entities={"company:nvidia"}, themes={"ai", "semiconductors", "data_center"},
         events={"EARNINGS"}),
    dict(headline="TSMC to build new chip factory in Arizona",
         summary="",
         entities={"company:tsmc"}, themes={"semiconductors"}, events={"CAPEX"}),
    dict(headline="生成AIブームで半導体製造装置の受注が急増",
         summary="",
         entities=set(), themes={"ai", "semiconductors"}, events=set()),
    # ---- rates / central bank ----
    dict(headline="Fed holds rates steady as Powell cites inflation risks",
         summary="",
         entities={"central_bank:fed", "person:jerome_powell"},
         themes={"inflation"}, events={"MONETARY_POLICY"}),
    dict(headline="日銀、利上げを見送り 円安が進行",
         summary="",
         entities={"central_bank:boj", "currency:JPY"},
         themes={"rates_monetary", "fx"}, events={"MONETARY_POLICY"}),
    dict(headline="ECB cuts interest rates for third time this year",
         summary="",
         entities={"central_bank:ecb"}, themes={"rates_monetary"},
         events={"MONETARY_POLICY"}),
    # ---- earnings / guidance ----
    dict(headline="トヨタ自動車、四半期利益が過去最高 業績予想を上方修正",
         summary="",
         entities={"company:toyota"}, themes=set(),
         events={"EARNINGS", "GUIDANCE"}),
    dict(headline="Sony raises forecast after strong quarterly results",
         summary="",
         entities={"company:sony"}, themes=set(), events={"EARNINGS", "GUIDANCE"}),
    # ---- geopolitics / defense ----
    dict(headline="US open to diplomacy after ninth night of bombing Iran",
         summary="",
         entities={"country:US", "country:IR"}, themes={"geopolitics"},
         events={"GEOPOLITICS"}),
    dict(headline="NATO members agree to boost defense spending",
         summary="",
         entities=set(), themes={"defense"}, events=set()),
    dict(headline="防衛費増額へ 防衛装備の国産化を推進",
         summary="",
         entities=set(), themes={"defense"}, events=set()),
    dict(headline="Russia and Ukraine agree ceasefire talks in Istanbul",
         summary="",
         entities={"country:RU", "country:UA"}, themes={"geopolitics"},
         events={"GEOPOLITICS"}),
    # ---- power / energy ----
    dict(headline="Data center boom strains the US power grid",
         summary="",
         entities={"country:US"}, themes={"data_center", "power", "grid"},
         events=set()),
    dict(headline="Japan restarts nuclear power plant to meet electricity demand",
         summary="",
         entities={"country:JP"}, themes={"nuclear", "power"}, events=set()),
    dict(headline="Oil prices surge after new sanctions on Russia",
         summary="",
         entities={"commodity:crude_oil", "country:RU"},
         themes={"energy", "geopolitics"}, events={"GEOPOLITICS", "PRICE_MOVE"}),
    # ---- ticker notation ----
    dict(headline="$NVDA and NASDAQ:MSFT lead tech rally",
         summary="",
         entities={"company:nvidia", "company:microsoft"}, themes=set(),
         events={"PRICE_MOVE"}),
    # ---- 曖昧語negative（何も付けない/付けすぎないのが正解） ----
    dict(headline="Apple falls from tree in Somerset orchard",
         summary="A record harvest this year.",
         entities=set(), themes=set(), events=set()),
    dict(headline="CAT scan technology improves at US hospitals",
         summary="",
         entities={"country:US"}, themes=set(), events=set()),
    dict(headline="Power outage hits city center",
         summary="",
         entities=set(), themes=set(), events=set()),
    dict(headline="He fed the dog and went to the market",
         summary="",
         entities=set(), themes=set(), events=set()),
    dict(headline="Hot tubs and £80 rosé: the festival gets a luxury makeover",
         summary="",
         entities=set(), themes=set(), events=set()),
    dict(headline="Arm wrestling championship comes to town",
         summary="",
         entities=set(), themes=set(), events=set()),
    # ---- 文脈でのlink成立 ----
    dict(headline="Apple unveils new iPhone with on-device AI",
         summary="",
         entities={"company:apple"}, themes=set(), events={"PRODUCT"}),
    dict(headline="Meta to spend billions on data center buildout",
         summary="Zuckerberg said AI infrastructure is the priority.",
         entities={"company:meta"}, themes={"ai", "data_center"}, events=set()),
    dict(headline="Arm Holdings shares jump after chip licensing deal",
         summary="",
         entities={"company:arm"}, themes=set(), events={"PRICE_MOVE"}),
    # ---- M&A / IPO / macro ----
    dict(headline="Nippon Steel completes acquisition of US rival",
         summary="",
         entities={"company:nippon_steel", "country:US"}, themes=set(), events={"MA"}),
    dict(headline="US CPI rises 3.1% as inflation stays sticky",
         summary="",
         entities={"country:US"}, themes={"inflation"}, events={"MACRO_DATA"}),
    dict(headline="Chip startup files for IPO on Nasdaq",
         summary="",
         entities=set(), themes=set(), events={"IPO"}),
    # ---- crypto / india / horizon ----
    dict(headline="Bitcoin hits record high above $150,000",
         summary="",
         entities={"currency:BTC"}, themes={"crypto"}, events={"PRICE_MOVE"}),
    dict(headline="Toyota plans to build EV plant in India by 2030",
         summary="",
         entities={"company:toyota", "country:IN"},
         themes={"india", "ev"}, events={"CAPEX"}, horizon={"YEARS"}),
]
