"""Article identity校正用ground-truth fixture（Phase 2-B）。

構成:
- 実データ由来ペア: tank 3,056件の全ペア類似度スキャンで見つかった
  **実在の高類似・別記事ペア**（誤結合ハザード。タイトルは実データ、summaryは
  当該記事の内容差を反映した最小限の合成）と、同日同一event別publisher実ペア。
- 合成ペア: SAME/REVISION/SYNDICATED（tank格納データはdedup済みで実重複が
  存在しないため、正例は合成で作る——P2-A identityシグナル分析の帰結）。

label語彙: SAME_ARTICLE / REVISION / SYNDICATED_COPY / DIFFERENT_ARTICLE / UNCERTAIN
期待判定: SAME_ARTICLE→EXACT_MATCH|AUTO_MERGE, REVISION→REVISION,
SYNDICATED_COPY→SYNDICATED, DIFFERENT_ARTICLE→CANDIDATE|DISTINCT（merge=false merge）,
UNCERTAIN→評価対象外（ただしmergeしないことを安全条件とする）
"""

# 各ペア: a=既存article member, b=新規判定対象
# フィールド: title, summary, url(空可), guid(空可), source, publisher, published(ISO)
PAIRS = [
    # ============ DIFFERENT_ARTICLE — 実tankハザード（数字違い高類似） ============
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: ECB年次カレンダー2027 vs 2028（sim 0.957・同日）",
        "a": {"title": "ECB publishes indicative operational calendars for 2027",
              "summary": "The ECB published the indicative calendar for reserve maintenance periods in 2027.",
              "url": "https://ecb.example/press/2027cal", "source": "ecb_press",
              "publisher": "European Central Bank", "published": "2026-06-30T10:00:00+00:00"},
        "b": {"title": "ECB publishes indicative operational calendars for 2028",
              "summary": "The ECB published the indicative calendar for reserve maintenance periods in 2028.",
              "url": "https://ecb.example/press/2028cal", "source": "ecb_press",
              "publisher": "European Central Bank", "published": "2026-06-30T10:05:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: Bloomberg日次連載 July 21 vs 22（sim 0.947）",
        "a": {"title": "Latest Oil Market News and Analysis for July 21",
              "summary": "Oil rose as traders weighed OPEC output signals ahead of inventory data.",
              "url": "https://bbg.example/oil-0721", "source": "bloomberg_markets",
              "publisher": "Bloomberg", "published": "2026-07-20T22:00:00+00:00"},
        "b": {"title": "Latest Oil Market News and Analysis for July 22",
              "summary": "Oil slipped after inventory build; traders eyed demand outlook.",
              "url": "https://bbg.example/oil-0722", "source": "bloomberg_markets",
              "publisher": "Bloomberg", "published": "2026-07-21T22:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: Federal Register Combined Notice #1 vs #2（sim 0.917・同日）",
        "a": {"title": "Combined Notice of Filings #1",
              "summary": "Take notice that the Commission received the following electric rate filings.",
              "url": "https://fedreg.example/cnf1", "source": "us_federal_register_energy",
              "publisher": "Federal Register", "published": "2026-07-21T12:00:00+00:00"},
        "b": {"title": "Combined Notice of Filings #2",
              "summary": "Take notice that the Commission received the following natural gas filings.",
              "url": "https://fedreg.example/cnf2", "source": "us_federal_register_energy",
              "publisher": "Federal Register", "published": "2026-07-21T12:10:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: Combined Notice #3 vs 無番号（sim 0.913・数字集合{3}vs{}）",
        "a": {"title": "Combined Notice of Filings #3",
              "summary": "Take notice that the Commission received the following electric corporate filings.",
              "url": "https://fedreg.example/cnf3", "source": "us_federal_register_energy",
              "publisher": "Federal Register", "published": "2026-07-09T12:00:00+00:00"},
        "b": {"title": "Combined Notice of Filings",
              "summary": "Take notice that the Commission received the following hydro filings.",
              "url": "https://fedreg.example/cnf0", "source": "us_federal_register_energy",
              "publisher": "Federal Register", "published": "2026-07-21T12:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: BBC Iran攻撃・連日報道の同型見出し（7/20 vs 7/21）",
        "a": {"title": "US launches fresh strikes on Iran, as Trump warns of retaliation",
              "summary": "Strikes hit military sites near Tehran on Monday, officials said.",
              "url": "https://bbc.example/iran-0720", "source": "bbc_world",
              "publisher": "BBC News", "published": "2026-07-20T06:00:00+00:00"},
        "b": {"title": "US launches fresh strikes on Iran, as Trump warns of retaliation",
              "summary": "A second wave of strikes targeted coastal facilities on Tuesday, with Kuwait reporting drone debris.",
              "url": "https://bbc.example/iran-0721", "source": "bbc_world",
              "publisher": "BBC News", "published": "2026-07-21T06:00:00+00:00"},
    },
    # ============ DIFFERENT_ARTICLE — 実データ: 同一event別publisher（別記事） ============
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: Houthis封鎖 CNA vs ABC（sim 0.580が実測最高値）",
        "a": {"title": "Yemen's Iran-backed Houthis announce maritime blockade on Saudi ports",
              "summary": "The group said vessels heading to Saudi ports would be targeted.",
              "url": "https://cna.example/houthi", "source": "cna_business",
              "publisher": "Channel News Asia", "published": "2026-07-20T08:00:00+00:00"},
        "b": {"title": "Iran-backed Houthis declare maritime blockade on Saudi Arabia",
              "summary": "Analysts said shipping insurers were reassessing Red Sea routes.",
              "url": "https://abc.example/houthi", "source": "abc_au_business",
              "publisher": "ABC News Australia", "published": "2026-07-20T09:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: 対加関税 Al Jazeera vs NPR（sim 0.477）",
        "a": {"title": "Trump imposes 50% US tariffs on some Canadian goods, citing trade imbalance",
              "summary": "The order covers lumber and dairy, with exemptions under review.",
              "url": "https://aj.example/tariff", "source": "aljazeera_all",
              "publisher": "Al Jazeera", "published": "2026-07-21T14:00:00+00:00"},
        "b": {"title": "Trump imposes 50% tariffs on Canadian goods",
              "summary": "Canadian officials called the measure unjustified and vowed to respond.",
              "url": "https://npr.example/tariff", "source": "npr_business",
              "publisher": "NPR", "published": "2026-07-21T15:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: 対加関税 ABC vs Guardian（sim 0.426）",
        "a": {"title": "US to impose 50pc tariffs on most Canadian goods",
              "summary": "The announcement rattled markets in Toronto.",
              "url": "https://abc.example/tariff", "source": "abc_au_business",
              "publisher": "ABC News Australia", "published": "2026-07-21T13:00:00+00:00"},
        "b": {"title": "Donald Trump to impose 50% tariff on most Canadian goods",
              "summary": "The Guardian understands exemptions for energy remain possible.",
              "url": "https://guardian.example/tariff", "source": "guardian_business",
              "publisher": "The Guardian", "published": "2026-07-21T16:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: 印活動家 BBC vs Al Jazeera（sim 0.426）",
        "a": {"title": "Indian activist on hunger strike for 20 days forcibly taken to hospital",
              "summary": "Doctors said his condition was stable after transfer.",
              "url": "https://bbc.example/activist", "source": "bbc_world",
              "publisher": "BBC News", "published": "2026-07-18T10:00:00+00:00"},
        "b": {"title": "Indian police forcibly hospitalise activist after 20-day hunger strike",
              "summary": "Rights groups criticised the police action as excessive.",
              "url": "https://aj.example/activist", "source": "aljazeera_all",
              "publisher": "Al Jazeera", "published": "2026-07-18T12:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "実データ: 山火事煙 CNBC vs SCMP（sim 0.414）",
        "a": {"title": "Trump rips Canada as wildfire smoke spreads, says U.S. will add tariffs",
              "summary": "Air quality alerts were issued across the Midwest.",
              "url": "https://cnbc.example/smoke", "source": "cnbc_markets",
              "publisher": "CNBC", "published": "2026-07-17T18:00:00+00:00"},
        "b": {"title": "Trump blames Canada for wildfire smoke, says he'll add tariffs",
              "summary": "Ottawa said the fires were being managed with federal support.",
              "url": "https://scmp.example/smoke", "source": "scmp_news",
              "publisher": "South China Morning Post", "published": "2026-07-17T20:00:00+00:00"},
    },
    # ============ DIFFERENT_ARTICLE — 合成（決算・定型・日本語） ============
    {
        "label": "DIFFERENT_ARTICLE", "note": "合成: 決算定型見出し・別社（数字違い）",
        "a": {"title": "トヨタ自動車、4〜6月期の営業利益は12%増　円安が寄与",
              "summary": "トヨタ自動車が発表した第1四半期決算は増益となった。",
              "url": "https://nikkei.example/toyota-q1", "source": "nikkei",
              "publisher": "日本経済新聞", "published": "2026-08-05T06:00:00+00:00"},
        "b": {"title": "ホンダ、4〜6月期の営業利益は8%増　二輪が寄与",
              "summary": "ホンダが発表した第1四半期決算は増益となった。",
              "url": "https://nikkei.example/honda-q1", "source": "nikkei",
              "publisher": "日本経済新聞", "published": "2026-08-06T06:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "合成: 日経平均の日次定型見出し（数字違い）",
        "a": {"title": "日経平均、一時4万2000円台に上昇　半導体株が牽引",
              "summary": "東京株式市場で日経平均株価は続伸した。",
              "url": "https://nhk.example/kabu-0828", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-08-28T02:00:00+00:00"},
        "b": {"title": "日経平均、一時4万1000円台に下落　利益確定売り",
              "summary": "東京株式市場で日経平均株価は反落した。",
              "url": "https://nhk.example/kabu-0829", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-08-29T02:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "合成: 米決算定型・別社",
        "a": {"title": "Acme Corp Q2 earnings beat estimates as cloud revenue jumps",
              "summary": "Acme reported quarterly revenue of $8.2 billion.",
              "url": "https://mw.example/acme-q2", "source": "marketwatch_top",
              "publisher": "MarketWatch", "published": "2026-07-25T20:10:00+00:00"},
        "b": {"title": "Zenith Corp Q2 earnings beat estimates as ad revenue jumps",
              "summary": "Zenith reported quarterly revenue of $5.6 billion.",
              "url": "https://mw.example/zenith-q2", "source": "marketwatch_top",
              "publisher": "MarketWatch", "published": "2026-07-25T21:00:00+00:00"},
    },
    {
        "label": "DIFFERENT_ARTICLE", "note": "合成: GDP速報 第1 vs 第2四半期（ja・数字違い）",
        "a": {"title": "第1四半期のGDP速報値、年率1.2%増",
              "summary": "内閣府が発表した1〜3月期のGDP速報値は年率換算で1.2%増だった。",
              "url": "https://nhk.example/gdp-q1", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-05-16T00:00:00+00:00"},
        "b": {"title": "第2四半期のGDP速報値、年率0.8%増",
              "summary": "内閣府が発表した4〜6月期のGDP速報値は年率換算で0.8%増だった。",
              "url": "https://nhk.example/gdp-q2", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-08-15T00:00:00+00:00"},
    },
    # ============ SAME_ARTICLE ============
    {
        "label": "SAME_ARTICLE", "note": "tracking違いの同一URL（canonical一致・同一内容）",
        "a": {"title": "BOJ keeps policy rate unchanged at July meeting",
              "summary": "The Bank of Japan held its policy rate, citing gradual inflation progress.",
              "url": "https://boj.example/mopo-july?utm_source=rss", "source": "boj_whatsnew",
              "publisher": "Bank of Japan", "published": "2026-07-31T03:30:00+00:00"},
        "b": {"title": "BOJ keeps policy rate unchanged at July meeting",
              "summary": "The Bank of Japan held its policy rate, citing gradual inflation progress.",
              "url": "https://boj.example/mopo-july?utm_medium=feed", "source": "boj_whatsnew",
              "publisher": "Bank of Japan", "published": "2026-07-31T03:30:00+00:00"},
    },
    {
        "label": "SAME_ARTICLE", "note": "同一source同一GUID同一内容（URL変更後の再配信）",
        "a": {"title": "Fed announces enhancements to payment services",
              "summary": "The Federal Reserve Board announced operational enhancements.",
              "url": "https://fed.example/press/old-path", "guid": "fed:pr:2026-104",
              "source": "fed_press", "publisher": "Federal Reserve",
              "published": "2026-08-12T14:00:00+00:00"},
        "b": {"title": "Fed announces enhancements to payment services",
              "summary": "The Federal Reserve Board announced operational enhancements.",
              "url": "https://fed.example/newsevents/press/new-path", "guid": "fed:pr:2026-104",
              "source": "fed_press", "publisher": "Federal Reserve",
              "published": "2026-08-12T14:00:00+00:00"},
    },
    {
        "label": "SAME_ARTICLE", "note": "実データ由来: BBCガスパイプライン（ハイフン編集のみ・sim 1.000）",
        "a": {"title": "West Africa signs off $25bn mega gas pipeline plan",
              "summary": "Leaders approved the pipeline linking Nigeria to Morocco after a decade of talks.",
              "url": "https://bbc.example/gas-a", "source": "bbc_business",
              "publisher": "BBC News", "published": "2026-07-20T09:00:00+00:00"},
        "b": {"title": "West Africa signs off $25bn mega gas-pipeline plan",
              "summary": "Leaders approved the pipeline linking Nigeria to Morocco after a decade of talks.",
              "url": "https://bbc.example/gas-b", "source": "bbc_business",
              "publisher": "BBC News", "published": "2026-07-20T10:30:00+00:00"},
    },
    {
        "label": "SAME_ARTICLE", "note": "合成: 軽微な見出し編集（en・冠詞追加）＋同一summary・近接時刻",
        "a": {"title": "BOJ holds rates steady as yen weakens past 150",
              "summary": "The central bank left its short-term rate target unchanged on Friday, noting currency moves.",
              "url": "https://jt.example/boj-a", "source": "japan_times",
              "publisher": "Japan Times", "published": "2026-08-01T05:00:00+00:00"},
        "b": {"title": "BOJ holds rates steady as the yen weakens past 150",
              "summary": "The central bank left its short-term rate target unchanged on Friday, noting currency moves.",
              "url": "https://jt.example/boj-b", "source": "japan_times",
              "publisher": "Japan Times", "published": "2026-08-01T06:00:00+00:00"},
    },
    {
        "label": "SAME_ARTICLE", "note": "合成: ja句読点・空白ゆれ＋同一summary",
        "a": {"title": "日銀、政策金利を維持　円安進行に警戒感",
              "summary": "日銀は金融政策決定会合で政策金利の維持を決めた。植田総裁は円安の物価影響に言及した。",
              "url": "https://nhk.example/boj-a", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-07-31T04:00:00+00:00"},
        "b": {"title": "日銀 政策金利を維持、円安進行に警戒感",
              "summary": "日銀は金融政策決定会合で政策金利の維持を決めた。植田総裁は円安の物価影響に言及した。",
              "url": "https://nhk.example/boj-b", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-07-31T04:30:00+00:00"},
    },
    {
        "label": "SAME_ARTICLE", "note": "同一fingerprint同一source・URL違い（内容完全一致）",
        "a": {"title": "EIA: US crude inventories fall for third week",
              "summary": "Commercial crude inventories decreased by 3.1 million barrels.",
              "url": "https://eia.example/weekly-a", "source": "eia_today",
              "publisher": "EIA", "published": "2026-08-20T15:00:00+00:00"},
        "b": {"title": "EIA: US crude inventories fall for third week",
              "summary": "Commercial crude inventories decreased by 3.1 million barrels.",
              "url": "https://eia.example/weekly-b", "source": "eia_today",
              "publisher": "EIA", "published": "2026-08-20T15:05:00+00:00"},
    },
    # ============ REVISION ============
    {
        "label": "REVISION", "note": "同一URL・内容更新（速報→詳報）",
        "a": {"title": "BOJ raises policy rate to 0.75%",
              "summary": "The Bank of Japan raised its policy rate. Details to follow.",
              "url": "https://reuters.example/boj-hike", "source": "reuters_business",
              "publisher": "Reuters", "published": "2026-09-19T03:05:00+00:00"},
        "b": {"title": "BOJ raises policy rate to 0.75%, first hike since January",
              "summary": "The Bank of Japan raised its policy rate to 0.75% and signalled a gradual path, sending the yen higher.",
              "url": "https://reuters.example/boj-hike", "source": "reuters_business",
              "publisher": "Reuters", "published": "2026-09-19T04:00:00+00:00"},
    },
    {
        "label": "REVISION", "note": "同一source同一GUID・内容更新",
        "a": {"title": "Magnitude 6.8 earthquake hits off Tohoku coast",
              "summary": "A strong quake struck off the coast. No tsunami warning was issued.",
              "url": "https://nhk.example/eq-1", "guid": "nhk:eq:20260815",
              "source": "nhk_general", "publisher": "NHK",
              "published": "2026-08-15T09:00:00+00:00"},
        "b": {"title": "Magnitude 6.8 earthquake hits off Tohoku coast; minor injuries reported",
              "summary": "A strong quake struck off the coast. Officials reported minor injuries and localized outages.",
              "url": "https://nhk.example/eq-1-updated", "guid": "nhk:eq:20260815",
              "source": "nhk_general", "publisher": "NHK",
              "published": "2026-08-15T11:00:00+00:00"},
    },
    {
        "label": "REVISION", "note": "ja同一URL・数値確定による更新",
        "a": {"title": "貿易収支、7月は赤字に",
              "summary": "財務省が発表した7月の貿易統計は赤字となった。",
              "url": "https://nhk.example/trade-july", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-08-21T00:10:00+00:00"},
        "b": {"title": "貿易収支、7月は6200億円の赤字　輸入増続く",
              "summary": "財務省が発表した7月の貿易統計は6200億円の赤字となった。エネルギー輸入の増加が続いた。",
              "url": "https://nhk.example/trade-july", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-08-21T01:00:00+00:00"},
    },
    # ============ SYNDICATED_COPY ============
    {
        "label": "SYNDICATED_COPY", "note": "Reuters→Yahoo型: 同一内容・別publisher・別URL",
        "a": {"title": "Dollar firms as traders trim Fed rate cut bets",
              "summary": "The dollar rose against major peers as strong data pushed back rate cut expectations.",
              "url": "https://reuters.example/fx-daily", "source": "reuters_business",
              "publisher": "Reuters", "published": "2026-08-22T07:00:00+00:00"},
        "b": {"title": "Dollar firms as traders trim Fed rate cut bets",
              "summary": "The dollar rose against major peers as strong data pushed back rate cut expectations.",
              "url": "https://news.yahoo.example/fx-daily", "source": "yahoo_jp_reuters",
              "publisher": "Yahoo!ニュース", "published": "2026-08-22T07:30:00+00:00"},
    },
    {
        "label": "SYNDICATED_COPY", "note": "ja転載: 同一内容・別relay",
        "a": {"title": "米FRB、政策金利を据え置き　年内利下げ示唆",
              "summary": "米連邦準備制度理事会は政策金利の据え置きを決定し、年内の利下げの可能性を示唆した。",
              "url": "https://reuters.example/fomc-ja", "source": "reuters_business",
              "publisher": "ロイター", "published": "2026-09-18T18:30:00+00:00"},
        "b": {"title": "米FRB、政策金利を据え置き　年内利下げ示唆",
              "summary": "米連邦準備制度理事会は政策金利の据え置きを決定し、年内の利下げの可能性を示唆した。",
              "url": "https://yahoo.example/fomc-ja", "source": "yahoo_jp_business",
              "publisher": "Yahoo!ニュース", "published": "2026-09-18T19:00:00+00:00"},
    },
    {
        "label": "SYNDICATED_COPY", "note": "wire→紙面: 同一内容・別紙",
        "a": {"title": "Oil steadies after OPEC+ keeps output policy unchanged",
              "summary": "Crude futures were little changed after the producer group maintained quotas.",
              "url": "https://cnbc.example/opec", "source": "cnbc_markets",
              "publisher": "CNBC", "published": "2026-08-03T12:00:00+00:00"},
        "b": {"title": "Oil steadies after OPEC+ keeps output policy unchanged",
              "summary": "Crude futures were little changed after the producer group maintained quotas.",
              "url": "https://mw.example/opec", "source": "marketwatch_top",
              "publisher": "MarketWatch", "published": "2026-08-03T12:20:00+00:00"},
    },
    # ============ UNCERTAIN ============
    {
        "label": "UNCERTAIN", "note": "実データ: SCMP HKEX（sim 0.958・改稿かも別記事かも判別不能）",
        "a": {"title": "HKEX to allow confidential filings, lower market cap thresholds",
              "summary": "The exchange proposed listing reforms to attract technology issuers.",
              "url": "https://scmp.example/hkex-a", "source": "scmp_news",
              "publisher": "South China Morning Post", "published": "2026-07-21T02:00:00+00:00"},
        "b": {"title": "HKEX to allow confidential filings, lower market cap threshold",
              "summary": "The exchange unveiled proposals covering listings and market thresholds for issuers.",
              "url": "https://scmp.example/hkex-b", "source": "scmp_news",
              "publisher": "South China Morning Post", "published": "2026-07-21T05:00:00+00:00"},
    },
    {
        "label": "UNCERTAIN", "note": "合成: en paraphrase（人間でも判定が割れる中間類似）",
        "a": {"title": "BOJ holds rates steady as yen weakens",
              "summary": "The central bank kept policy unchanged, watching currency moves.",
              "url": "https://a.example/boj", "source": "japan_times",
              "publisher": "Japan Times", "published": "2026-08-01T05:00:00+00:00"},
        "b": {"title": "BOJ keeps rates steady while yen weakens",
              "summary": "Policymakers left settings unchanged amid a soft currency.",
              "url": "https://b.example/boj", "source": "cna_business",
              "publisher": "CNA", "published": "2026-08-01T06:00:00+00:00"},
    },
    {
        "label": "UNCERTAIN", "note": "合成: ja paraphrase",
        "a": {"title": "日銀、政策金利を維持　円安進行",
              "summary": "日銀は政策金利を維持した。外国為替市場では円安が進んだ。",
              "url": "https://a.example/boj-ja", "source": "nhk_business",
              "publisher": "NHK", "published": "2026-07-31T04:00:00+00:00"},
        "b": {"title": "日銀が政策金利を維持、円安が進行",
              "summary": "日本銀行は金利の維持を決定。円相場は下落した。",
              "url": "https://b.example/boj-ja", "source": "yahoo_jp_business",
              "publisher": "Yahoo!ニュース", "published": "2026-07-31T05:00:00+00:00"},
    },
]

# 実tank由来のtitle-onlyハザードコーパス（40ペア・類似度0.60〜0.91）。
# ground-truthラベルは付けない（改題/別記事の判別は人間でも困難なペアを含む）。
# 安全条件として使う: summary（内容証拠）なしではいかなるペアもmergeされないこと。
TANK_HAZARD_TITLE_PAIRS = [
    {"sim": 0.908, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.906, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_b": "2026-07-13T04:00:00+00:00"},
    {"sim": 0.905, "source": "scmp_com", "publisher": "South China Morning Post — News",
     "title_a": "Ex-Hong Kong fencer jailed 41 months for role in laundering HK$10.6 million", "published_a": "2026-07-21T11:02:35+00:00",
     "title_b": "Ex-Hong Kong fencer jailed for 41 months for role in laundering HK$10.6 million", "published_b": "2026-07-21T11:02:35+00:00"},
    {"sim": 0.894, "source": "scmp_com", "publisher": "South China Morning Post — News",
     "title_a": "Z.ai shares surge 37% as firm builds giant data centre powered by Chinese chips", "published_a": "2026-07-21T12:42:10+00:00",
     "title_b": "Zhipu shares surge 37% as firm builds giant data centre powered by Chinese chips", "published_b": "2026-07-21T12:42:10+00:00"},
    {"sim": 0.89, "source": "marketwatch_com", "publisher": "MarketWatch — Top Stories",
     "title_a": "The co-founder of Stocktwits dumped chip stocks before a 20% slide. Where he’s putting his money now.", "published_a": "2026-07-21T11:11:00+00:00",
     "title_b": "The co-founder of Stocktwits dumped chip stocks before their 20% slide. Where he’s putting his money now.", "published_b": "2026-07-21T11:47:00+00:00"},
    {"sim": 0.889, "source": "defensenews_com", "publisher": "Defense News — Latest",
     "title_a": "Pentagon identifies American soliders killed in Iranian attack in Jordan", "published_a": "2026-07-20T15:47:49+00:00",
     "title_b": "Pentagon identifies American soldiers killed in Iranian attack in Jordan", "published_b": "2026-07-20T15:47:49+00:00"},
    {"sim": 0.882, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "PJM Governance and Stakeholder Reforms; Second Supplemental Notice of Commission-Led Technical Conference", "published_a": "2026-07-08T04:00:00+00:00",
     "title_b": "PJM Governance and Stakeholder Reforms; Third Supplemental Notice of Commission-Led Technical Conference", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.877, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.877, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_b": "2026-07-13T04:00:00+00:00"},
    {"sim": 0.875, "source": "fsa_go_jp", "publisher": "金融庁 — 新着情報",
     "title_a": "記者会見,片山財務大臣兼内閣府特命担当大臣閣議後記者会見の概要（令和８年７月17日）について掲載しました。", "published_a": "2026-07-21T17:00:00+00:00",
     "title_b": "記者会見,片山財務大臣兼内閣府特命担当大臣閣議後記者会見の概要（令和８年７月14日）について掲載しました。", "published_b": "2026-07-21T16:59:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_b": "2026-07-13T04:00:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_b": "2026-07-13T04:00:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.864, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.852, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Revisions to Financial Forms Reporting and Filing Requirements", "published_a": "2026-06-24T04:00:00+00:00",
     "title_b": "Revisions to Financial Forms Reporting and Filing Requirements; Correction", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.848, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_b": "2026-07-13T04:00:00+00:00"},
    {"sim": 0.848, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.848, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.844, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activity (FERC-730); Comment Request; Extension", "published_a": "2026-06-30T04:00:00+00:00",
     "title_b": "Commission Information Collection Activity (Ferc-555); Comment Request; Extension", "published_b": "2026-07-10T04:00:00+00:00"},
    {"sim": 0.84, "source": "boj_or_jp", "publisher": "Bank of Japan — What's New (English)",
     "title_a": "Bank of Japan Accounts (June 20)", "published_a": "2026-06-23T01:00:00+00:00",
     "title_b": "Bank of Japan Accounts (June 30)", "published_b": "2026-07-02T01:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (Ferc-521); Comment Request; Extension", "published_a": "2026-07-13T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-561); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.836, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-912); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
    {"sim": 0.836, "source": "bbc_co_uk", "publisher": "BBC News — World",
     "title_a": "'Anti-ICE' Army veteran set fire outside Manhattan federal building, say officials", "published_a": "2026-07-21T02:16:05+00:00",
     "title_b": "'Anti-ICE' army veteran started fire outside Manhattan federal building, say officials", "published_b": "2026-07-21T02:16:05+00:00"},
    {"sim": 0.836, "source": "allafrica_com", "publisher": "AllAfrica — Headlines",
     "title_a": "Nigeria: Breaking - Captured 'Ansaru Leaders' Make U-Turn, Plead Guilty to 32 Terrorism Charges", "published_a": "2026-07-20T14:33:25+00:00",
     "title_b": "Nigeria: Captured 'Ansaru Leaders' Make U-Turn, Plead Guilty to 32 Terrorism Charges", "published_b": "2026-07-21T05:42:26+00:00"},
    {"sim": 0.831, "source": "marketwatch_com", "publisher": "MarketWatch — Top Stories",
     "title_a": "I will claim Social Security early. Why do so few people talk about the elephant in the room?", "published_a": "2026-07-20T10:30:00+00:00",
     "title_b": "I will definitely claim Social Security early. Why do so few people talk about the elephant in the room?", "published_b": "2026-07-21T20:30:00+00:00"},
    {"sim": 0.824, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549D); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.824, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-549C); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-725S); Comment Request; Extension", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.811, "source": "investors_com", "publisher": "Yahoo Finance — News",
     "title_a": "Charles Schwab Earnings Due As Interactive Brokers Awaits", "published_a": "2026-07-21T11:00:11+00:00",
     "title_b": "Charles Schwab Earnings Beat As Interactive Brokers Awaits", "published_b": "2026-07-21T12:15:56+00:00"},
    {"sim": 0.797, "source": "scmp_com", "publisher": "South China Morning Post — News",
     "title_a": "Chinese AI agent outperforms Anthropic’s Claude Code in autonomous research", "published_a": "2026-07-21T12:17:32+00:00",
     "title_b": "Chinese AI agent Qiushi Engine outperforms Anthropic’s Claude Code in autonomous research", "published_b": "2026-07-21T12:17:32+00:00"},
    {"sim": 0.791, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_a": "2026-07-07T04:00:00+00:00",
     "title_b": "Commission Information Collection Activity (Ferc-555); Comment Request; Extension", "published_b": "2026-07-10T04:00:00+00:00"},
    {"sim": 0.785, "source": "scmp_com", "publisher": "South China Morning Post — News",
     "title_a": "Perfume ban, no-fly zone – as Apec summit looms, Shenzhen is ramping up security", "published_a": "2026-07-21T08:07:47+00:00",
     "title_b": "Perfume ban, no-fly zone – as Apec summit looms, Shenzhen ramps up security", "published_b": "2026-07-21T08:07:47+00:00"},
    {"sim": 0.784, "source": "cnbc_com", "publisher": "CNBC — Markets",
     "title_a": "Jim Cramer's top 10 things to watch in the stock market Monday", "published_a": "2026-07-20T12:53:55+00:00",
     "title_b": "Jim Cramer's top 10 things to watch in the stock market Tuesday", "published_b": "2026-07-21T13:05:47+00:00"},
    {"sim": 0.784, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Guardian Pipeline, LLC; Notice of Application and Establishing Intervention Deadline", "published_a": "2026-07-17T04:00:00+00:00",
     "title_b": "ETC Tiger Pipeline, LLC; Notice of Application and Establishing Intervention Deadline", "published_b": "2026-07-21T04:00:00+00:00"},
    {"sim": 0.778, "source": "federalregister_gov", "publisher": "U.S. Federal Register — Energy Dept documents",
     "title_a": "Commission Information Collection Activities (FERC-516); Comment Request; Merger; Extension", "published_a": "2026-06-25T04:00:00+00:00",
     "title_b": "Commission Information Collection Activities (FERC-556); Comment Request; Extension", "published_b": "2026-07-07T04:00:00+00:00"},
]
